- hosts: azure_ubuntu
  vars:
    erlang_version: 1:25.3.2.2-1
    rabbitmq_version: 3.11.19-1
  tasks:
  - name: 1. Install needed packages
    become: true
    ansible.builtin.apt:
      pkg:
      - curl
      - gnupg
      - apt-transport-https
  - name: 2. One way to avoid apt_key once it is removed from your distro
    block:
      - name: 2-1. Add Erlang gpg key
        become: true
        apt_key:
          url: https://ppa1.novemberain.com/gpg.E495BB49CC4BBE5B.key
          state: present
        register: _add_apt_key
        until: _add_apt_key is succeeded
        retries: 5
        delay: 2
      - name: 2-2. Add RabbitMQ gpg key
        become: true
        apt_key:
          url: https://ppa1.novemberain.com/gpg.9F4587F226208342.key
          state: present
        register: _add_apt_rabbitmq_key
        until: _add_apt_rabbitmq_key is succeeded
        retries: 5
        delay: 2
      - name: 2-3. Add Erlang repository
        become: true
        ansible.builtin.apt_repository:
          repo: deb https://ppa1.novemberain.com/rabbitmq/rabbitmq-erlang/deb/ubuntu {{ ansible_distribution_release }} main
          state: present
          filename: erlang-repo
      - name: 2-4. Add RabbitMQ repository
        become: true
        ansible.builtin.apt_repository:
          repo: deb https://ppa1.novemberain.com/rabbitmq/rabbitmq-server/deb/ubuntu {{ ansible_distribution_release }} main
          state: present
          filename: rabbitmq-repo
  - name: 3. Add Pin preference
    become: true
    template: src=./prefernece.j2 dest=/etc/apt/preferences.d/erlang_rabbitmq
  - name: 4. Update Cache and apply policy
    become: true
    ansible.builtin.shell: apt update -y && apt policy
  - name: 5. Install Erlang and RabbitMQ
    become: true
    apt:
      package:
        - "erlang-nox={{erlang_version}}"
        - "rabbitmq-server={{rabbitmq_version}}"
      state: present
      install_recommends: false